database:
  Username: your_db_username
  Password: your_db_password
  Host: localhost
  Port: "3306"
  Name: your_db_name

redis:
  Host: localhost
  Port: "6379"
  Password: your_redis_password
